language: php
php:
    -  '5.6'
    -  '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
 - wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
 - sudo php-cs-fixer self-update

script:
 - php php-cs-fixer --dry-run -v fix .

notifications:
  email: true
