language: php
php:
  - '5.6'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer global require friendsofphp/php-cs-fixer
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - ./composer.phar global update friendsofphp/php-cs-fixer

script:
  - php php-cs-fixer.phar fix .

notifications:
  email: true

deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: testesgiiw
  on:
    repo: ESGI-IW1-GROUPE3/test-commits
